### ISSUE TITLE
host cloud app

### ISSUE THREAD

**Issue by ProgrammingGoldflash** [d-velop/dvelop-app-template-go#19]
Why do I have to publish/deploy the app with AWS. Can't I just host it on my own server or customers server?

**Comment by mtestrot** [comment]
You can.
The template has 2 go commands (executables). A lambda package for an AWS based deployment and a windows executable. Cf. https://github.com/d-velop/dvelop-app-template-go/blob/master/cmd/app/main.go
Just execute the normal buildprocess with `docker-build build` and take the executable from the `dist` directory.
