### ISSUE TITLE
Update AWS CLI version to awscli v2

### ISSUE THREAD

**Issue by vincent-elbracht** [d-velop/dvelop-app-template-go#20]
**OLD** /buildcontainer/Dockerfile line. 60-63:
`RUN curl -sSL https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip && \`
`    unzip awscli-bundle.zip && \`
`    ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && \`
`    rm awscli-bundle.zip && rm -rf ./awscli-bundle`

**CHANGE TO:**
`RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \`
`    unzip awscliv2.zip && \`
`    ./aws/install -i /usr/local/aws -b /usr/local/bin && \`
`    rm awscliv2.zip && rm -rf ./aws`

**Comment by mtestrot** [comment]
resolved
