### ISSUE TITLE
Support of authenticating an App Outside the User Context

### ISSUE THREAD

**Issue by 85LangA85** [d-velop/dvelop-app-template-go#4]
To authenticate an App Outside the User Context, the new Feature of the Identityprovider is needed. Please Support the Apikey Functions.

[https://developer.d-velop.de/documentation/dipa/de/d-ecs-identity-provider-api-125187928.html#section-5](url)

**Comment by mtestrot** [comment]
Moved to https://github.com/d-velop/dvelop-sdk-go/issues/3
